### ISSUE TITLE
Write Codes for the Problems

### ISSUE THREAD

**Issue by deepdarshan21** [dscnsec/DSC-NSEC-Algorithms#10]

**Comment by deepdarshan21** [comment]
@ani4aniket @ritesh-chafer @anjali1903 @srpsatish can I start working on this issue

**Comment by anjali1903** [comment]
Hi @deepdarshan21 . This repository is for the Winter of Code program. Feel free to submit a proposal for the same. For more details, visit winterofcode.com :)
