### ISSUE TITLE
Pull Request Template

### ISSUE THREAD

**Issue by Vishal-raj-1** [dscnsec/DSC-NSEC-Algorithms#6]
### Solution of Question Name

- [ ] Code is added in right directory(Folder).
- [ ] Brief Description of Solution is given.
- [ ] Time and Space Complexity is mentioned
- [ ] Code is well indented.
- [ ] Comments are clearly written wherever necessary
- [ ] Code is successfully compiled and passes all test cases.

@anjali1903 Please add this pull request template for this repo.

**Comment by anjali1903** [comment]
Thank you for your suggestion. It will help in improving the quality of the repository.
