### ISSUE TITLE
weird_sorting.md

### ISSUE THREAD

**Issue by Vishal-raj-1** [dscnsec/DSC-NSEC-Algorithms#8]
In Question it is : _The bags are filled with either 7 or 21 or 49 coins._

But in Example :
1
10
7 21 7 7 7 21 14 14 21 7

14 giving instead of 49. Although  It Doesn't Matter, But you can look at it. @anjali1903

**Comment by anjali1903** [comment]
Thank you for pointing out the mistake. It will be corrected.
